/-
Copyright (c) 2021-2026 by the authors listed in the file AUTHORS and their
institutional affiliations. All rights reserved.
Released under Apache 2.0 license as described in the file LICENSE.
Authors: Haniel Barbosa
-/

-- GENERATED by `Smt/Alethe/Rare/gen.py` from `rewrites.eo` (sha256 24c508375431).
-- Regenerate after changing the rule file; the proofs below are preserved, everything else is
-- overwritten. A theorem proved by `sorry` makes the checker report its rule as trusted.

module

public import Smt.Alethe.Rare.Basic
public import Smt.Alethe.Lemmas
public import Smt.Reconstruct.Prop.Rewrites
public import Smt.Reconstruct.Builtin.Rewrites
public import Smt.Reconstruct.UF.Rewrites
public import Smt.Reconstruct.Int.Rewrites
public import Smt.Reconstruct.Rat.Rewrites

@[expose] public section

-- premises a proof does not need
set_option linter.unusedVariables false

namespace Smt.Alethe.Rare

open Smt.Reconstruct

universe u


-- rare: arith-div-total-zero-real (int)
/-- `(= (/ t1 0/1) 0/1)` -/
theorem arith_div_total_zero_real_int (t1 : Int) :
    ((↑t1 : Rat) / 0) = 0 :=
  Rat.Rewrite.div_total_zero

-- rare: arith-div-total-zero-real (rat)
/-- `(= (/ t1 0/1) 0/1)` -/
theorem arith_div_total_zero_real_rat (t1 : Rat) :
    (t1 / 0) = 0 :=
  Rat.Rewrite.div_total_zero

-- rare: arith-div-total-zero-int (int)
/-- `(= (/ t1 0) 0/1)` -/
theorem arith_div_total_zero_int_int (t1 : Int) :
    ((↑t1 : Rat) / 0) = 0 :=
  Rat.Rewrite.div_total_zero

-- rare: arith-div-total-zero-int (rat)
/-- `(= (/ t1 0) 0/1)` -/
theorem arith_div_total_zero_int_rat (t1 : Rat) :
    (t1 / 0) = 0 :=
  Rat.Rewrite.div_total_zero

-- rare: arith-int-div-total-zero
/-- `(= (div t1 0) 0)` -/
theorem arith_int_div_total_zero (t1 : Int) :
    (t1 / 0) = 0 :=
  Int.Rewrite.div_total_zero

-- rare: arith-int-mod-total-zero
/-- `(= (mod t1 0) t1)` -/
theorem arith_int_mod_total_zero (t1 : Int) :
    (t1 % 0) = t1 :=
  Int.Rewrite.mod_total_zero

-- rare: arith-int-div-total
/-- `(= (div t1 s1) (div t1 s1))` -/
theorem arith_int_div_total (t1 s1 : Int) (h1 : (s1 = 0) = False) :
    (t1 / s1) = (t1 / s1) :=
  Int.Rewrite.div_total h1

-- rare: arith-int-div-total-one
/-- `(= (div t1 1) t1)` -/
theorem arith_int_div_total_one (t1 : Int) :
    (t1 / 1) = t1 :=
  Int.Rewrite.div_total_one

-- rare: arith-int-div-total-neg
/-- `(= (div t1 s1) (- (div t1 (- s1))))` -/
theorem arith_int_div_total_neg (t1 s1 : Int) (h1 : (s1 < 0) = True) :
    (t1 / s1) = (-(t1 / (-s1))) :=
  Int.Rewrite.div_total_neg h1

-- rare: arith-int-mod-total
/-- `(= (mod t1 s1) (mod t1 s1))` -/
theorem arith_int_mod_total (t1 s1 : Int) (h1 : (s1 = 0) = False) :
    (t1 % s1) = (t1 % s1) :=
  Int.Rewrite.mod_total h1

-- rare: arith-int-mod-total-one
/-- `(= (mod t1 1) 0)` -/
theorem arith_int_mod_total_one (t1 : Int) :
    (t1 % 1) = 0 :=
  Int.Rewrite.mod_total_one

-- rare: arith-int-mod-total-neg
/-- `(= (mod t1 s1) (mod t1 (- s1)))` -/
theorem arith_int_mod_total_neg (t1 s1 : Int) (h1 : (s1 < 0) = True) :
    (t1 % s1) = (t1 % (-s1)) :=
  Int.Rewrite.mod_total_neg h1

-- rare: arith-elim-gt (int)
/-- `(= (> t1 s1) (not (>= s1 t1)))` -/
theorem arith_elim_gt_int (t1 s1 : Int) :
    (t1 > s1) = (¬(s1 ≥ t1)) :=
  Int.Rewrite.elim_gt

-- rare: arith-elim-gt (rat)
/-- `(= (> t1 s1) (not (>= s1 t1)))` -/
theorem arith_elim_gt_rat (t1 s1 : Rat) :
    (t1 > s1) = (¬(s1 ≥ t1)) :=
  Rat.Rewrite.elim_gt

-- rare: arith-elim-lt (int)
/-- `(= (< t1 s1) (not (>= t1 s1)))` -/
theorem arith_elim_lt_int (t1 s1 : Int) :
    (t1 < s1) = (¬(t1 ≥ s1)) :=
  Int.Rewrite.elim_lt

-- rare: arith-elim-lt (rat)
/-- `(= (< t1 s1) (not (>= t1 s1)))` -/
theorem arith_elim_lt_rat (t1 s1 : Rat) :
    (t1 < s1) = (¬(t1 ≥ s1)) :=
  Rat.Rewrite.elim_lt

-- rare: arith-elim-int-gt
/-- `(= (> t1 s1) (>= t1 (+ s1 1)))` -/
theorem arith_elim_int_gt (t1 s1 : Int) :
    (t1 > s1) = (t1 ≥ (s1 + 1)) :=
  Int.Rewrite.elim_gt_add_one

-- rare: arith-elim-int-lt
/-- `(= (< t1 s1) (>= s1 (+ t1 1)))` -/
theorem arith_elim_int_lt (t1 s1 : Int) :
    (t1 < s1) = (s1 ≥ (t1 + 1)) :=
  Int.Rewrite.elim_lt_add_one

-- rare: arith-elim-leq (int)
/-- `(= (<= t1 s1) (>= s1 t1))` -/
theorem arith_elim_leq_int (t1 s1 : Int) :
    (t1 ≤ s1) = (s1 ≥ t1) :=
  Int.Rewrite.elim_leq

-- rare: arith-elim-leq (rat)
/-- `(= (<= t1 s1) (>= s1 t1))` -/
theorem arith_elim_leq_rat (t1 s1 : Rat) :
    (t1 ≤ s1) = (s1 ≥ t1) :=
  Rat.Rewrite.elim_leq

-- rare: arith-leq-norm
/-- `(= (<= t1 s1) (not (>= t1 (+ s1 1))))` -/
theorem arith_leq_norm (t1 s1 : Int) :
    (t1 ≤ s1) = (¬(t1 ≥ (s1 + 1))) :=
  Int.Rewrite.leq_norm

-- rare: arith-geq-tighten
/-- `(= (not (>= t1 s1)) (>= s1 (+ t1 1)))` -/
theorem arith_geq_tighten (t1 s1 : Int) :
    (¬(t1 ≥ s1)) = (s1 ≥ (t1 + 1)) :=
  Int.Rewrite.geq_tighten

-- rare: arith-geq-norm1-int
/-- `(= (>= t1 s1) (>= (- t1 s1) 0))` -/
theorem arith_geq_norm1_int (t1 s1 : Int) :
    (t1 ≥ s1) = ((t1 - s1) ≥ 0) :=
  Int.Rewrite.geq_norm1

-- rare: arith-geq-norm1-real
/-- `(= (>= t1 s1) (>= (- t1 s1) 0/1))` -/
theorem arith_geq_norm1_real (t1 s1 : Rat) :
    (t1 ≥ s1) = ((t1 - s1) ≥ 0) :=
  Rat.Rewrite.geq_norm1

-- rare: arith-eq-elim-real
/-- `(= (= t1 s1) (and (>= t1 s1) (<= t1 s1)))` -/
theorem arith_eq_elim_real (t1 s1 : Rat) :
    (t1 = s1) = ((t1 ≥ s1) ∧ (t1 ≤ s1)) :=
  Rat.Rewrite.eq_elim

-- rare: arith-eq-elim-int
/-- `(= (= t1 s1) (and (>= t1 s1) (<= t1 s1)))` -/
theorem arith_eq_elim_int (t1 s1 : Int) :
    (t1 = s1) = ((t1 ≥ s1) ∧ (t1 ≤ s1)) :=
  Int.Rewrite.eq_elim

-- rare: arith-to-int-elim-to-real (int)
/-- `(= (to_int (to_real x1)) (to_int x1))` -/
theorem arith_to_int_elim_to_real_int (x1 : Int) :
    ((↑x1 : Rat).floor) = ((↑x1 : Rat).floor) :=
  rfl

-- rare: arith-to-int-elim-to-real (rat)
/-- `(= (to_int (to_real x1)) (to_int x1))` -/
theorem arith_to_int_elim_to_real_rat (x1 : Rat) :
    x1.floor = x1.floor :=
  rfl

-- rare: arith-div-elim-to-real1 (int)
/-- `(= (/ (to_real x1) y1) (/ x1 y1))` -/
theorem arith_div_elim_to_real1_int (x1 y1 : Int) :
    ((↑x1 : Rat) / (↑y1 : Rat)) = ((↑x1 : Rat) / (↑y1 : Rat)) :=
  rfl

-- rare: arith-div-elim-to-real1 (rat)
/-- `(= (/ (to_real x1) y1) (/ x1 y1))` -/
theorem arith_div_elim_to_real1_rat (x1 y1 : Rat) :
    (x1 / y1) = (x1 / y1) :=
  rfl

-- rare: arith-div-elim-to-real2 (int)
/-- `(= (/ x1 (to_real y1)) (/ x1 y1))` -/
theorem arith_div_elim_to_real2_int (x1 y1 : Int) :
    ((↑x1 : Rat) / (↑y1 : Rat)) = ((↑x1 : Rat) / (↑y1 : Rat)) :=
  rfl

-- rare: arith-div-elim-to-real2 (rat)
/-- `(= (/ x1 (to_real y1)) (/ x1 y1))` -/
theorem arith_div_elim_to_real2_rat (x1 y1 : Rat) :
    (x1 / y1) = (x1 / y1) :=
  rfl

-- rare: arith-mod-over-mod
/-- `(= (mod (+ ts1 (mod r1 c1) ss1) c1) (mod (+ ts1 r1 ss1) c1))` -/
theorem arith_mod_over_mod (c1 : Int) (ts1 : List Int) (r1 : Int) (ss1 : List Int) (h1 : (c1 = 0) = False) :
    ((Int.addN (ts1 ++ ((r1 % c1) :: ss1))) % c1) = ((Int.addN (ts1 ++ (r1 :: ss1))) % c1) :=
  Int.Rewrite.mod_over_mod h1

-- rare: arith-int-eq-conflict
/-- `(= (= (to_real t1) c1) false)` -/
theorem arith_int_eq_conflict (t1 : Int) (c1 : Rat) (h1 : ((↑c1.floor : Rat) = c1) = False) :
    ((↑t1 : Rat) = c1) = False :=
  Rat.Rewrite.eq_conflict h1

-- rare: arith-int-geq-tighten
/-- `(= (>= (to_real t1) c1) (>= t1 cc1))` -/
theorem arith_int_geq_tighten (t1 : Int) (c1 : Rat) (cc1 : Int) (h1 : ((↑c1.floor : Rat) = c1) = False) (h2 : cc1 = (c1.floor + 1)) :
    ((↑t1 : Rat) ≥ c1) = (t1 ≥ cc1) :=
  Rat.Rewrite.geq_tighten h1 h2

-- rare: arith-abs-eq (int)
/-- `(= (= (abs x1) (abs y1)) (or (= x1 y1) (= x1 (- y1))))` -/
theorem arith_abs_eq_int (x1 y1 : Int) :
    (x1.abs = y1.abs) = ((x1 = y1) ∨ (x1 = (-y1))) :=
  Int.Rewrite.abs_eq

-- rare: arith-abs-eq (rat)
/-- `(= (= (abs x1) (abs y1)) (or (= x1 y1) (= x1 (- y1))))` -/
theorem arith_abs_eq_rat (x1 y1 : Rat) :
    (x1.abs = y1.abs) = ((x1 = y1) ∨ (x1 = (-y1))) :=
  Rat.Rewrite.abs_eq

-- rare: arith-abs-int-gt
/-- `(= (> (abs x1) (abs y1)) (let ((_let_1 (- y1))) (let ((_let_2 (- x1))) (let ((_let_3 (>= y1 0))) (ite (>= x1 0) (ite _let_3 (> x1 y1) (> x1 _let_1)) (ite _let_3 (> _let_2 y1) (> _let_2 _let_1)))))))` -/
theorem arith_abs_int_gt (x1 y1 : Int) :
    (x1.abs > y1.abs) = (ite (x1 ≥ 0) (ite (y1 ≥ 0) (x1 > y1) (x1 > (-y1))) (ite (y1 ≥ 0) ((-x1) > y1) ((-x1) > (-y1)))) :=
  Int.Rewrite.abs_gt

-- rare: arith-abs-real-gt
/-- `(= (> (abs x1) (abs y1)) (let ((_let_1 (- y1))) (let ((_let_2 (- x1))) (let ((_let_3 (>= y1 0/1))) (ite (>= x1 0/1) (ite _let_3 (> x1 y1) (> x1 _let_1)) (ite _let_3 (> _let_2 y1) (> _let_2 _let_1)))))))` -/
theorem arith_abs_real_gt (x1 y1 : Rat) :
    (x1.abs > y1.abs) = (ite (x1 ≥ 0) (ite (y1 ≥ 0) (x1 > y1) (x1 > (-y1))) (ite (y1 ≥ 0) ((-x1) > y1) ((-x1) > (-y1)))) :=
  Rat.Rewrite.abs_gt

-- rare: arith-geq-ite-lift (int)
/-- `(= (>= (ite C1 t1 s1) r1) (ite C1 (>= t1 r1) (>= s1 r1)))` -/
theorem arith_geq_ite_lift_int (C1 : Prop) [Decidable C1] (t1 s1 r1 : Int) :
    ((ite C1 t1 s1) ≥ r1) = (ite C1 (t1 ≥ r1) (s1 ≥ r1)) :=
  Int.Rewrite.geq_ite_lift

-- rare: arith-geq-ite-lift (rat)
/-- `(= (>= (ite C1 t1 s1) r1) (ite C1 (>= t1 r1) (>= s1 r1)))` -/
theorem arith_geq_ite_lift_rat (C1 : Prop) [Decidable C1] (t1 s1 r1 : Rat) :
    ((ite C1 t1 s1) ≥ r1) = (ite C1 (t1 ≥ r1) (s1 ≥ r1)) :=
  Rat.Rewrite.geq_ite_lift

-- rare: arith-leq-ite-lift (int)
/-- `(= (<= (ite C1 t1 s1) r1) (ite C1 (<= t1 r1) (<= s1 r1)))` -/
theorem arith_leq_ite_lift_int (C1 : Prop) [Decidable C1] (t1 s1 r1 : Int) :
    ((ite C1 t1 s1) ≤ r1) = (ite C1 (t1 ≤ r1) (s1 ≤ r1)) :=
  Int.Rewrite.leq_ite_lift

-- rare: arith-leq-ite-lift (rat)
/-- `(= (<= (ite C1 t1 s1) r1) (ite C1 (<= t1 r1) (<= s1 r1)))` -/
theorem arith_leq_ite_lift_rat (C1 : Prop) [Decidable C1] (t1 s1 r1 : Rat) :
    ((ite C1 t1 s1) ≤ r1) = (ite C1 (t1 ≤ r1) (s1 ≤ r1)) :=
  Rat.Rewrite.leq_ite_lift

-- rare: arith-min-lt1 (int)
/-- `(= (<= (ite (< t1 s1) t1 s1) t1) true)` -/
theorem arith_min_lt1_int (t1 s1 : Int) :
    ((ite (t1 < s1) t1 s1) ≤ t1) = True :=
  Int.Rewrite.min_lt1

-- rare: arith-min-lt1 (rat)
/-- `(= (<= (ite (< t1 s1) t1 s1) t1) true)` -/
theorem arith_min_lt1_rat (t1 s1 : Rat) :
    ((ite (t1 < s1) t1 s1) ≤ t1) = True :=
  Rat.Rewrite.min_lt1

-- rare: arith-min-lt2 (int)
/-- `(= (<= (ite (< t1 s1) t1 s1) s1) true)` -/
theorem arith_min_lt2_int (t1 s1 : Int) :
    ((ite (t1 < s1) t1 s1) ≤ s1) = True :=
  Int.Rewrite.min_lt2

-- rare: arith-min-lt2 (rat)
/-- `(= (<= (ite (< t1 s1) t1 s1) s1) true)` -/
theorem arith_min_lt2_rat (t1 s1 : Rat) :
    ((ite (t1 < s1) t1 s1) ≤ s1) = True :=
  Rat.Rewrite.min_lt2

-- rare: arith-max-geq1 (int)
/-- `(= (>= (ite (>= t1 s1) t1 s1) t1) true)` -/
theorem arith_max_geq1_int (t1 s1 : Int) :
    ((ite (t1 ≥ s1) t1 s1) ≥ t1) = True :=
  Int.Rewrite.max_geq1

-- rare: arith-max-geq1 (rat)
/-- `(= (>= (ite (>= t1 s1) t1 s1) t1) true)` -/
theorem arith_max_geq1_rat (t1 s1 : Rat) :
    ((ite (t1 ≥ s1) t1 s1) ≥ t1) = True :=
  Rat.Rewrite.max_geq1

-- rare: arith-max-geq2 (int)
/-- `(= (>= (ite (>= t1 s1) t1 s1) s1) true)` -/
theorem arith_max_geq2_int (t1 s1 : Int) :
    ((ite (t1 ≥ s1) t1 s1) ≥ s1) = True :=
  Int.Rewrite.max_geq2

-- rare: arith-max-geq2 (rat)
/-- `(= (>= (ite (>= t1 s1) t1 s1) s1) true)` -/
theorem arith_max_geq2_rat (t1 s1 : Rat) :
    ((ite (t1 ≥ s1) t1 s1) ≥ s1) = True :=
  Rat.Rewrite.max_geq2

-- rare: bool-double-not-elim
/-- `(= (not (not t1)) t1)` -/
theorem bool_double_not_elim (t1 : Prop) :
    (¬(¬t1)) = t1 :=
  Prop.bool_double_not_elim

-- rare: bool-not-true
/-- `(= (not t1) true)` -/
theorem bool_not_true (t1 : Prop) (h1 : t1 = False) :
    (¬t1) = True :=
  Prop.bool_not_true h1

-- rare: bool-not-false
/-- `(= (not t1) false)` -/
theorem bool_not_false (t1 : Prop) (h1 : t1 = True) :
    (¬t1) = False :=
  Prop.bool_not_false h1

-- rare: bool-eq-true
/-- `(= (= t1 true) t1)` -/
theorem bool_eq_true (t1 : Prop) :
    (t1 = True) = t1 :=
  Prop.bool_eq_true

-- rare: bool-eq-false
/-- `(= (= t1 false) (not t1))` -/
theorem bool_eq_false (t1 : Prop) :
    (t1 = False) = (¬t1) :=
  Prop.bool_eq_false

-- rare: bool-eq-nrefl
/-- `(= (= x1 (not x1)) false)` -/
theorem bool_eq_nrefl (x1 : Prop) :
    (x1 = (¬x1)) = False :=
  Prop.bool_eq_nrefl

-- rare: bool-impl-false1
/-- `(= (=> t1 false) (not t1))` -/
theorem bool_impl_false1 (t1 : Prop) :
    (t1 → False) = (¬t1) :=
  Prop.bool_impl_false1

-- rare: bool-impl-false2
/-- `(= (=> false t1) true)` -/
theorem bool_impl_false2 (t1 : Prop) :
    (False → t1) = True :=
  Prop.bool_impl_false2

-- rare: bool-impl-true1
/-- `(= (=> t1 true) true)` -/
theorem bool_impl_true1 (t1 : Prop) :
    (t1 → True) = True :=
  Prop.bool_impl_true1

-- rare: bool-impl-true2
/-- `(= (=> true t1) t1)` -/
theorem bool_impl_true2 (t1 : Prop) :
    (True → t1) = t1 :=
  Prop.bool_impl_true2

-- rare: bool-impl-elim
/-- `(= (=> t1 s1) (or (not t1) s1))` -/
theorem bool_impl_elim (t1 s1 : Prop) :
    (t1 → s1) = ((¬t1) ∨ s1) :=
  Prop.bool_impl_elim

-- rare: bool-dual-impl-eq
/-- `(= (and (=> t1 s1) (=> s1 t1)) (= t1 s1))` -/
theorem bool_dual_impl_eq (t1 s1 : Prop) :
    ((t1 → s1) ∧ (s1 → t1)) = (t1 = s1) :=
  Prop.bool_dual_impl_eq

-- rare: bool-and-conf
/-- `(= (and xs1 w1 ys1 (not w1) zs1) false)` -/
theorem bool_and_conf (xs1 : List Prop) (w1 : Prop) (ys1 zs1 : List Prop) :
    (andN (xs1 ++ (w1 :: (ys1 ++ ((¬w1) :: zs1))))) = False :=
  Prop.bool_and_conf

-- rare: bool-and-conf2
/-- `(= (and xs1 (not w1) ys1 w1 zs1) false)` -/
theorem bool_and_conf2 (xs1 : List Prop) (w1 : Prop) (ys1 zs1 : List Prop) :
    (andN (xs1 ++ ((¬w1) :: (ys1 ++ (w1 :: zs1))))) = False :=
  Prop.bool_and_conf2

-- rare: bool-or-taut
/-- `(= (or xs1 w1 ys1 (not w1) zs1) true)` -/
theorem bool_or_taut (xs1 : List Prop) (w1 : Prop) (ys1 zs1 : List Prop) :
    (orN (xs1 ++ (w1 :: (ys1 ++ ((¬w1) :: zs1))))) = True :=
  Prop.bool_or_taut

-- rare: bool-or-taut2
/-- `(= (or xs1 (not w1) ys1 w1 zs1) true)` -/
theorem bool_or_taut2 (xs1 : List Prop) (w1 : Prop) (ys1 zs1 : List Prop) :
    (orN (xs1 ++ ((¬w1) :: (ys1 ++ (w1 :: zs1))))) = True :=
  Prop.bool_or_taut2

-- rare: bool-or-de-morgan
/-- `(= (not (or x1 y1 zs1)) (and (not x1) (not (or y1 zs1))))` -/
theorem bool_or_de_morgan (x1 y1 : Prop) (zs1 : List Prop) :
    (¬(orN (x1 :: (y1 :: zs1)))) = ((¬x1) ∧ (¬(orN (y1 :: zs1)))) :=
  Prop.bool_or_de_morgan

-- rare: bool-implies-de-morgan
/-- `(= (not (=> x1 y1)) (and x1 (not y1)))` -/
theorem bool_implies_de_morgan (x1 y1 : Prop) :
    (¬(x1 → y1)) = (x1 ∧ (¬y1)) :=
  Prop.bool_implies_de_morgan

-- rare: bool-and-de-morgan
/-- `(= (not (and x1 y1 zs1)) (or (not x1) (not (and y1 zs1))))` -/
theorem bool_and_de_morgan (x1 y1 : Prop) (zs1 : List Prop) :
    (¬(andN (x1 :: (y1 :: zs1)))) = ((¬x1) ∨ (¬(andN (y1 :: zs1)))) :=
  Prop.bool_and_de_morgan

-- rare: bool-or-and-distrib
/-- `(= (or (and y1 y2 ys1) z1 zs1) (and (or y1 z1 zs1) (or (and y2 ys1) z1 zs1)))` -/
theorem bool_or_and_distrib (y1 y2 : Prop) (ys1 : List Prop) (z1 : Prop) (zs1 : List Prop) :
    (orN ((andN (y1 :: (y2 :: ys1))) :: (z1 :: zs1))) = ((orN (y1 :: (z1 :: zs1))) ∧ (orN ((andN (y2 :: ys1)) :: (z1 :: zs1)))) :=
  Prop.bool_or_and_distrib

-- rare: bool-implies-or-distrib
/-- `(= (=> (or y1 y2 ys1) z1) (and (=> y1 z1) (=> (or y2 ys1) z1)))` -/
theorem bool_implies_or_distrib (y1 y2 : Prop) (ys1 : List Prop) (z1 : Prop) :
    ((orN (y1 :: (y2 :: ys1))) → z1) = ((y1 → z1) ∧ ((orN (y2 :: ys1)) → z1)) :=
  Prop.bool_implies_or_distrib

-- rare: bool-xor-refl
/-- `(= (xor x1 x1) false)` -/
theorem bool_xor_refl (x1 : Prop) :
    (XOr x1 x1) = False :=
  Prop.bool_xor_refl

-- rare: bool-xor-nrefl
/-- `(= (xor x1 (not x1)) true)` -/
theorem bool_xor_nrefl (x1 : Prop) :
    (XOr x1 (¬x1)) = True :=
  Prop.bool_xor_nrefl

-- rare: bool-xor-false
/-- `(= (xor x1 false) x1)` -/
theorem bool_xor_false (x1 : Prop) :
    (XOr x1 False) = x1 :=
  Prop.bool_xor_false

-- rare: bool-xor-true
/-- `(= (xor x1 true) (not x1))` -/
theorem bool_xor_true (x1 : Prop) :
    (XOr x1 True) = (¬x1) :=
  Prop.bool_xor_true

-- rare: bool-xor-comm
/-- `(= (xor x1 y1) (xor y1 x1))` -/
theorem bool_xor_comm (x1 y1 : Prop) :
    (XOr x1 y1) = (XOr y1 x1) :=
  Prop.bool_xor_comm

-- rare: bool-xor-elim
/-- `(= (xor x1 y1) (= (not x1) y1))` -/
theorem bool_xor_elim (x1 y1 : Prop) :
    (XOr x1 y1) = ((¬x1) = y1) :=
  Prop.bool_xor_elim

-- rare: bool-not-xor-elim
/-- `(= (not (xor x1 y1)) (= x1 y1))` -/
theorem bool_not_xor_elim (x1 y1 : Prop) :
    (¬(XOr x1 y1)) = (x1 = y1) :=
  Prop.bool_not_xor_elim

-- rare: bool-not-eq-elim1
/-- `(= (not (= x1 y1)) (= (not x1) y1))` -/
theorem bool_not_eq_elim1 (x1 y1 : Prop) :
    (¬(x1 = y1)) = ((¬x1) = y1) :=
  Prop.bool_not_eq_elim1

-- rare: bool-not-eq-elim2
/-- `(= (not (= x1 y1)) (= x1 (not y1)))` -/
theorem bool_not_eq_elim2 (x1 y1 : Prop) :
    (¬(x1 = y1)) = (x1 = (¬y1)) :=
  Prop.bool_not_eq_elim2

-- rare: ite-neg-branch
/-- `(= (ite c1 x1 y1) (= c1 x1))` -/
theorem ite_neg_branch (c1 : Prop) [Decidable c1] (x1 y1 : Prop) (h1 : (¬y1) = x1) :
    (ite c1 x1 y1) = (c1 = x1) :=
  Prop.ite_neg_branch h1.symm

-- rare: ite-then-true
/-- `(= (ite c1 true x1) (or c1 x1))` -/
theorem ite_then_true (c1 : Prop) [Decidable c1] (x1 : Prop) :
    (ite c1 True x1) = (c1 ∨ x1) :=
  Prop.ite_then_true

-- rare: ite-else-false
/-- `(= (ite c1 x1 false) (and c1 x1))` -/
theorem ite_else_false (c1 : Prop) [Decidable c1] (x1 : Prop) :
    (ite c1 x1 False) = (c1 ∧ x1) :=
  Prop.ite_else_false

-- rare: ite-then-false
/-- `(= (ite c1 false x1) (and (not c1) x1))` -/
theorem ite_then_false (c1 : Prop) [Decidable c1] (x1 : Prop) :
    (ite c1 False x1) = ((¬c1) ∧ x1) :=
  Prop.ite_then_false

-- rare: ite-else-true
/-- `(= (ite c1 x1 true) (or (not c1) x1))` -/
theorem ite_else_true (c1 : Prop) [Decidable c1] (x1 : Prop) :
    (ite c1 x1 True) = ((¬c1) ∨ x1) :=
  Prop.ite_else_true

-- rare: ite-then-lookahead-self
/-- `(= (ite c1 c1 x1) (ite c1 true x1))` -/
theorem ite_then_lookahead_self (c1 : Prop) [Decidable c1] (x1 : Prop) :
    (ite c1 c1 x1) = (ite c1 True x1) :=
  Prop.ite_then_lookahead_self

-- rare: ite-else-lookahead-self
/-- `(= (ite c1 x1 c1) (ite c1 x1 false))` -/
theorem ite_else_lookahead_self (c1 : Prop) [Decidable c1] (x1 : Prop) :
    (ite c1 x1 c1) = (ite c1 x1 False) :=
  Prop.ite_else_lookahead_self

-- rare: ite-then-lookahead-not-self
/-- `(= (ite c1 (not c1) x1) (ite c1 false x1))` -/
theorem ite_then_lookahead_not_self (c1 : Prop) [Decidable c1] (x1 : Prop) :
    (ite c1 (¬c1) x1) = (ite c1 False x1) :=
  Prop.ite_then_lookahead_not_self

-- rare: ite-else-lookahead-not-self
/-- `(= (ite c1 x1 (not c1)) (ite c1 x1 true))` -/
theorem ite_else_lookahead_not_self (c1 : Prop) [Decidable c1] (x1 : Prop) :
    (ite c1 x1 (¬c1)) = (ite c1 x1 True) :=
  Prop.ite_else_lookahead_not_self

-- rare: ite-expand
/-- `(= (ite c1 x1 y1) (and (or (not c1) x1) (or c1 y1)))` -/
theorem ite_expand (c1 : Prop) [Decidable c1] (x1 y1 : Prop) :
    (ite c1 x1 y1) = (((¬c1) ∨ x1) ∧ (c1 ∨ y1)) :=
  Prop.ite_expand

-- rare: bool-not-ite-elim
/-- `(= (not (ite c1 x1 y1)) (ite c1 (not x1) (not y1)))` -/
theorem bool_not_ite_elim (c1 : Prop) [Decidable c1] (x1 y1 : Prop) :
    (¬(ite c1 x1 y1)) = (ite c1 (¬x1) (¬y1)) :=
  Prop.bool_not_ite_elim

-- rare: ite-true-cond
/-- `(= (ite true x1 y1) x1)` -/
theorem ite_true_cond {α : Sort u} (x1 y1 : α) :
    (ite True x1 y1) = x1 :=
  Builtin.ite_true_cond

-- rare: ite-false-cond
/-- `(= (ite false x1 y1) y1)` -/
theorem ite_false_cond {α : Sort u} (x1 y1 : α) :
    (ite False x1 y1) = y1 :=
  Builtin.ite_false_cond

-- rare: ite-not-cond
/-- `(= (ite (not c1) x1 y1) (ite c1 y1 x1))` -/
theorem ite_not_cond {α : Sort u} (c1 : Prop) [Decidable c1] (x1 y1 : α) :
    (ite (¬c1) x1 y1) = (ite c1 y1 x1) :=
  Builtin.ite_not_cond

-- rare: ite-eq-branch
/-- `(= (ite c1 x1 x1) x1)` -/
theorem ite_eq_branch {α : Sort u} (c1 : Prop) [Decidable c1] (x1 : α) :
    (ite c1 x1 x1) = x1 :=
  Builtin.ite_eq_branch

-- rare: ite-then-lookahead
/-- `(= (ite c1 (ite c1 x1 y1) z1) (ite c1 x1 z1))` -/
theorem ite_then_lookahead {α : Sort u} (c1 : Prop) [Decidable c1] (x1 y1 z1 : α) :
    (ite c1 (ite c1 x1 y1) z1) = (ite c1 x1 z1) :=
  Builtin.ite_then_lookahead

-- rare: ite-else-lookahead
/-- `(= (ite c1 x1 (ite c1 y1 z1)) (ite c1 x1 z1))` -/
theorem ite_else_lookahead {α : Sort u} (c1 : Prop) [Decidable c1] (x1 y1 z1 : α) :
    (ite c1 x1 (ite c1 y1 z1)) = (ite c1 x1 z1) :=
  Builtin.ite_else_lookahead

-- rare: ite-then-neg-lookahead
/-- `(= (ite c1 (ite (not c1) x1 y1) z1) (ite c1 y1 z1))` -/
theorem ite_then_neg_lookahead {α : Sort u} (c1 : Prop) [Decidable c1] (x1 y1 z1 : α) :
    (ite c1 (ite (¬c1) x1 y1) z1) = (ite c1 y1 z1) :=
  Builtin.ite_then_neg_lookahead

-- rare: ite-else-neg-lookahead
/-- `(= (ite c1 x1 (ite (not c1) y1 z1)) (ite c1 x1 y1))` -/
theorem ite_else_neg_lookahead {α : Sort u} (c1 : Prop) [Decidable c1] (x1 y1 z1 : α) :
    (ite c1 x1 (ite (¬c1) y1 z1)) = (ite c1 x1 y1) :=
  Builtin.ite_else_neg_lookahead

-- rare: eq-refl
/-- `(= (= t1 t1) true)` -/
theorem eq_refl {α : Sort u} (t1 : α) :
    (t1 = t1) = True :=
  UF.eq_refl

-- rare: eq-symm
/-- `(= (= t1 s1) (= s1 t1))` -/
theorem eq_symm {α : Sort u} (t1 s1 : α) :
    (t1 = s1) = (s1 = t1) :=
  UF.eq_symm

-- rare: eq-cond-deq
/-- `(= (= (= t1 s1) (= t1 r1)) (and (not (= t1 s1)) (not (= t1 r1))))` -/
theorem eq_cond_deq {α : Sort u} (t1 s1 r1 : α) (h1 : (s1 = r1) = False) :
    ((t1 = s1) = (t1 = r1)) = ((¬(t1 = s1)) ∧ (¬(t1 = r1))) :=
  UF.eq_cond_deq h1

-- rare: eq-ite-lift
/-- `(= (= (ite C1 t1 s1) r1) (ite C1 (= t1 r1) (= s1 r1)))` -/
theorem eq_ite_lift {α : Sort u} (C1 : Prop) [Decidable C1] (t1 s1 r1 : α) :
    ((ite C1 t1 s1) = r1) = (ite C1 (t1 = r1) (s1 = r1)) :=
  UF.eq_ite_lift

-- rare: distinct-binary-elim
/-- `(= (distinct t1 s1) (not (= t1 s1)))` -/
theorem distinct_binary_elim {α : Sort u} (t1 s1 : α) :
    (t1 ≠ s1) = (¬(t1 = s1)) :=
  UF.distinct_binary_elim

-- rare: arith-mod-over-mod-1
/-- `(= (mod (mod r c) c) (mod r c))` -/
theorem arith_mod_over_mod_1 (c r : Int) (h1 : (c = 0) = False) :
    ((r % c) % c) = (r % c) :=
  Int.emod_emod r c

-- rare: ite-eq
/-- `(= (ite C (= (ite C t1 t2) t1) (= (ite C t1 t2) t2)) true)` -/
theorem ite_eq {α : Sort u} (C : Prop) [Decidable C] (t1 t2 : α) :
    (ite C ((ite C t1 t2) = t1) ((ite C t1 t2) = t2)) = True :=
  by by_cases h : C <;> simp [h]

-- rare: or-not-refl
/-- `(= (or (not (= t t)) xs) (or xs))` -/
theorem or_not_refl {α : Sort u} (t : α) (xs : List Prop) :
    (orN ((¬(t = t)) :: xs)) = (orN xs) :=
  Smt.Alethe.or_not_refl t xs

-- rare: bool-not-eq-false
/-- `(= (not (= t t)) false)` -/
theorem bool_not_eq_false (t : Prop) :
    (¬(t = t)) = False :=
  propext ⟨fun h => h rfl, False.elim⟩

-- rare: mod-elim
/-- `(= (mod a b) (- a (* b (div a b))))` -/
theorem mod_elim (a b : Int) :
    (a % b) = (a - (b * (a / b))) :=
  Int.emod_def a b

-- rare: is_int-elim
/-- `(= (is_int x) (= x (to_real (to_int x))))` -/
theorem is_int_elim (x : Rat) :
    (x = ↑x.floor) = (x = (↑x.floor : Rat)) :=
  rfl

-- rare: abs-elim-int
/-- `(= (abs t) (ite (< t 0) (- t) t))` -/
theorem abs_elim_int (t : Int) :
    t.abs = (ite (t < 0) (-t) t) :=
  rfl

-- rare: abs-elim-real
/-- `(= (abs t) (ite (< t 0/1) (- t) t))` -/
theorem abs_elim_real (t : Rat) :
    t.abs = (ite (t < 0) (-t) t) :=
  by
  unfold Rat.abs
  by_cases h : t < 0
  · rw [if_pos h, if_neg (Rat.not_le.mpr h)]
  · rw [if_neg h, if_pos (Rat.not_lt.mp h)]

-- rare: mult-tangent-lower (int)
/-- `(= (<= (* x y) (- (+ (* b x) (* a y)) (* a b))) (or (and (<= x a) (>= y b)) (and (>= x a) (<= y b))))` -/
theorem mult_tangent_lower_int (x y a b : Int) :
    ((x * y) ≤ (((b * x) + (a * y)) - (a * b))) = (((x ≤ a) ∧ (y ≥ b)) ∨ ((x ≥ a) ∧ (y ≤ b))) :=
  sorry

-- rare: mult-tangent-lower (rat)
/-- `(= (<= (* x y) (- (+ (* b x) (* a y)) (* a b))) (or (and (<= x a) (>= y b)) (and (>= x a) (<= y b))))` -/
theorem mult_tangent_lower_rat (x y a b : Rat) :
    ((x * y) ≤ (((b * x) + (a * y)) - (a * b))) = (((x ≤ a) ∧ (y ≥ b)) ∨ ((x ≥ a) ∧ (y ≤ b))) :=
  sorry

-- rare: mult-tangent-upper (int)
/-- `(= (>= (* x y) (- (+ (* b x) (* a y)) (* a b))) (or (and (<= x a) (<= y b)) (and (>= x a) (>= y b))))` -/
theorem mult_tangent_upper_int (x y a b : Int) :
    ((x * y) ≥ (((b * x) + (a * y)) - (a * b))) = (((x ≤ a) ∧ (y ≤ b)) ∨ ((x ≥ a) ∧ (y ≥ b))) :=
  sorry

-- rare: mult-tangent-upper (rat)
/-- `(= (>= (* x y) (- (+ (* b x) (* a y)) (* a b))) (or (and (<= x a) (<= y b)) (and (>= x a) (>= y b))))` -/
theorem mult_tangent_upper_rat (x y a b : Rat) :
    ((x * y) ≥ (((b * x) + (a * y)) - (a * b))) = (((x ≤ a) ∧ (y ≤ b)) ∨ ((x ≥ a) ∧ (y ≥ b))) :=
  sorry

-- end rare-rules

/-! Rules without a Lean statement (reported as trusted):
  - `array-read-over-write`: unsupported sort (Array @T0 @T1)
  - `array-read-over-write2`: unsupported sort (Array @T0 @T1)
  - `array-store-overwrite`: unsupported sort (Array @T0 @T1)
  - `array-store-self`: unsupported sort (Array @T0 @T1)
  - `array-read-over-write-split`: unsupported sort (Array @T0 @T1)
  - `array-store-swap`: unsupported sort (Array @T0 @T1)
  - `distinct-false`: n-ary distinct
-/

/-- The rule file itself, for handing to Carcara (`--rare-file`) from a tactic. -/
def ruleFileText : String :=
  r#"; TODO this rule and the next three are not necessarily things we want to have as valid
(declare-rare-rule arith-div-total-zero-real ((@T0 Type) (t1 @T0))
  :args (t1)
  :conclusion (= (/ t1 0/1) 0/1)
)
(declare-rare-rule arith-div-total-zero-int ((@T0 Type) (t1 @T0))
  :args (t1)
  :conclusion (= (/ t1 0) 0/1)
)
(declare-rare-rule arith-int-div-total-zero ((t1 Int))
  :args (t1)
  :conclusion (= (div t1 0) 0)
)
(declare-rare-rule arith-int-mod-total-zero ((t1 Int))
  :args (t1)
  :conclusion (= (mod t1 0) t1)
)

;; TODO artifact of cvc5's new totalized operators
(declare-rare-rule arith-int-div-total ((t1 Int) (s1 Int))
  :premises ((= (= s1 0) false))
  :args (t1 s1)
  :conclusion (= (div t1 s1) (div t1 s1))
)
(declare-rare-rule arith-int-div-total-one ((t1 Int))
  :args (t1)
  :conclusion (= (div t1 1) t1)
)

(declare-rare-rule arith-int-div-total-neg ((t1 Int) (s1 Int))
  :premises ((= (< s1 0) true))
  :args (t1 s1)
  :conclusion (= (div t1 s1) (- (div t1 (- s1))))
)
(declare-rare-rule arith-int-mod-total ((t1 Int) (s1 Int))
  :premises ((= (= s1 0) false))
  :args (t1 s1)
  :conclusion (= (mod t1 s1) (mod t1 s1))
)
(declare-rare-rule arith-int-mod-total-one ((t1 Int))
  :args (t1)
  :conclusion (= (mod t1 1) 0)
)
(declare-rare-rule arith-int-mod-total-neg ((t1 Int) (s1 Int))
  :premises ((= (< s1 0) true))
  :args (t1 s1)
  :conclusion (= (mod t1 s1) (mod t1 (- s1)))
)
(declare-rare-rule arith-elim-gt ((@T0 Type) (@T1 Type) (t1 @T0) (s1 @T1))
  :args (t1 s1)
  :conclusion (= (> t1 s1) (not (>= s1 t1)))
)
(declare-rare-rule arith-elim-lt ((@T0 Type) (@T1 Type) (t1 @T0) (s1 @T1))
  :args (t1 s1)
  :conclusion (= (< t1 s1) (not (>= t1 s1)))
)
(declare-rare-rule arith-elim-int-gt ((t1 Int) (s1 Int))
  :args (t1 s1)
  :conclusion (= (> t1 s1) (>= t1 (+ s1 1)))
)
(declare-rare-rule arith-elim-int-lt ((t1 Int) (s1 Int))
  :args (t1 s1)
  :conclusion (= (< t1 s1) (>= s1 (+ t1 1)))
)
(declare-rare-rule arith-elim-leq ((@T0 Type) (@T1 Type) (t1 @T0) (s1 @T1))
  :args (t1 s1)
  :conclusion (= (<= t1 s1) (>= s1 t1))
)
(declare-rare-rule arith-leq-norm ((t1 Int) (s1 Int))
  :args (t1 s1)
  :conclusion (= (<= t1 s1) (not (>= t1 (+ s1 1))))
)
(declare-rare-rule arith-geq-tighten ((t1 Int) (s1 Int))
  :args (t1 s1)
  :conclusion (= (not (>= t1 s1)) (>= s1 (+ t1 1)))
)
(declare-rare-rule arith-geq-norm1-int ((t1 Int) (s1 Int))
  :args (t1 s1)
  :conclusion (= (>= t1 s1) (>= (- t1 s1) 0))
)
(declare-rare-rule arith-geq-norm1-real ((t1 Real) (s1 Real))
  :args (t1 s1)
  :conclusion (= (>= t1 s1) (>= (- t1 s1) 0/1))
)
(declare-rare-rule arith-eq-elim-real ((t1 Real) (s1 Real))
  :args (t1 s1)
  :conclusion (= (= t1 s1) (and (>= t1 s1) (<= t1 s1)))
)
(declare-rare-rule arith-eq-elim-int ((t1 Int) (s1 Int))
  :args (t1 s1)
  :conclusion (= (= t1 s1) (and (>= t1 s1) (<= t1 s1)))
)
;; (declare-rare-rule arith-to-int-elim ((x1 Int))
;;   :args (x1)
;;   :conclusion (= (to_int x1) x1)
;; )
(declare-rare-rule arith-to-int-elim-to-real ((@T0 Type) (x1 @T0))
  :args (x1)
  :conclusion (= (to_int (to_real x1)) (to_int x1))
)
(declare-rare-rule arith-div-elim-to-real1 ((@T0 Type) (@T1 Type) (x1 @T0) (y1 @T1))
  :args (x1 y1)
  :conclusion (= (/ (to_real x1) y1) (/ x1 y1))
)
(declare-rare-rule arith-div-elim-to-real2 ((@T0 Type) (@T1 Type) (x1 @T0) (y1 @T1))
  :args (x1 y1)
  :conclusion (= (/ x1 (to_real y1)) (/ x1 y1))
)
(declare-rare-rule arith-mod-over-mod ((c1 Int) (ts1 Int :list) (r1 Int) (ss1 Int :list))
  :premises ((= (= c1 0) false))
  :args (c1 ts1 r1 ss1)
  :conclusion (= (mod (+ ts1 (mod r1 c1) ss1) c1) (mod (+ ts1 r1 ss1) c1))
)
(declare-rare-rule arith-int-eq-conflict ((t1 Int) (c1 Real))
  :premises ((= (= (to_real (to_int c1)) c1) false))
  :args (t1 c1)
  :conclusion (= (= (to_real t1) c1) false)
)
(declare-rare-rule arith-int-geq-tighten ((t1 Int) (c1 Real) (cc1 Int))
  :premises ((= (= (to_real (to_int c1)) c1) false) (= cc1 (+ (to_int c1) 1)))
  :args (t1 c1 cc1)
  :conclusion (= (>= (to_real t1) c1) (>= t1 cc1))
)
;; (declare-rare-rule arith-divisible-elim ((n1 Int) (t1 Int))
;;   :premises ((= (= n1 0) false))
;;   :args (n1 t1)
;;   :conclusion (= (divisible n1 t1) (= (mod t1 n1) 0))
;; )
(declare-rare-rule arith-abs-eq ((@T0 Type) (@T1 Type) (x1 @T0) (y1 @T1))
  :args (x1 y1)
  :conclusion (= (= (abs x1) (abs y1)) (or (= x1 y1) (= x1 (- y1))))
)
(declare-rare-rule arith-abs-int-gt ((x1 Int) (y1 Int))
  :args (x1 y1)
  :conclusion (= (> (abs x1) (abs y1)) (let ((_let_1 (- y1))) (let ((_let_2 (- x1))) (let ((_let_3 (>= y1 0))) (ite (>= x1 0) (ite _let_3 (> x1 y1) (> x1 _let_1)) (ite _let_3 (> _let_2 y1) (> _let_2 _let_1)))))))
)
(declare-rare-rule arith-abs-real-gt ((x1 Real) (y1 Real))
  :args (x1 y1)
  :conclusion (= (> (abs x1) (abs y1)) (let ((_let_1 (- y1))) (let ((_let_2 (- x1))) (let ((_let_3 (>= y1 0/1))) (ite (>= x1 0/1) (ite _let_3 (> x1 y1) (> x1 _let_1)) (ite _let_3 (> _let_2 y1) (> _let_2 _let_1)))))))
)
(declare-rare-rule arith-geq-ite-lift ((@T0 Type) (@T1 Type) (@T2 Type) (C1 Bool) (t1 @T0) (s1 @T1) (r1 @T2))
  :args (C1 t1 s1 r1)
  :conclusion (= (>= (ite C1 t1 s1) r1) (ite C1 (>= t1 r1) (>= s1 r1)))
)
(declare-rare-rule arith-leq-ite-lift ((@T0 Type) (@T1 Type) (@T2 Type) (C1 Bool) (t1 @T0) (s1 @T1) (r1 @T2))
  :args (C1 t1 s1 r1)
  :conclusion (= (<= (ite C1 t1 s1) r1) (ite C1 (<= t1 r1) (<= s1 r1)))
)
(declare-rare-rule arith-min-lt1 ((@T0 Type) (@T1 Type) (t1 @T0) (s1 @T1))
  :args (t1 s1)
  :conclusion (= (<= (ite (< t1 s1) t1 s1) t1) true)
)
(declare-rare-rule arith-min-lt2 ((@T0 Type) (@T1 Type) (t1 @T0) (s1 @T1))
  :args (t1 s1)
  :conclusion (= (<= (ite (< t1 s1) t1 s1) s1) true)
)
(declare-rare-rule arith-max-geq1 ((@T0 Type) (@T1 Type) (t1 @T0) (s1 @T1))
  :args (t1 s1)
  :conclusion (= (>= (ite (>= t1 s1) t1 s1) t1) true)
)
(declare-rare-rule arith-max-geq2 ((@T0 Type) (@T1 Type) (t1 @T0) (s1 @T1))
  :args (t1 s1)
  :conclusion (= (>= (ite (>= t1 s1) t1 s1) s1) true)
)
(declare-rare-rule array-read-over-write ((@T0 Type) (@T1 Type) (@T2 Type) (@T3 Type) (t1 (Array @T0 @T1)) (i1 @T2) (e1 @T3))
  :args (t1 i1 e1)
  :conclusion (= (select (store t1 i1 e1) i1) e1)
)
(declare-rare-rule array-read-over-write2 ((@T0 Type) (@T1 Type) (@T2 Type) (@T3 Type) (@T4 Type) (t1 (Array @T0 @T1)) (i1 @T2) (j1 @T3) (e1 @T4))
  :premises ((= (= i1 j1) false))
  :args (t1 i1 j1 e1)
  :conclusion (= (select (store t1 i1 e1) j1) (select t1 j1))
)
(declare-rare-rule array-store-overwrite ((@T0 Type) (@T1 Type) (@T2 Type) (@T3 Type) (@T4 Type) (t1 (Array @T0 @T1)) (i1 @T2) (e1 @T3) (f1 @T4))
  :args (t1 i1 e1 f1)
  :conclusion (= (store (store t1 i1 e1) i1 f1) (store t1 i1 f1))
)
(declare-rare-rule array-store-self ((@T0 Type) (@T1 Type) (@T2 Type) (t1 (Array @T0 @T1)) (i1 @T2))
  :args (t1 i1)
  :conclusion (= (store t1 i1 (select t1 i1)) t1)
)
(declare-rare-rule array-read-over-write-split ((@T0 Type) (@T1 Type) (@T2 Type) (@T3 Type) (@T4 Type) (t1 (Array @T0 @T1)) (i1 @T2) (e1 @T3) (j1 @T4))
  :args (t1 i1 e1 j1)
  :conclusion (= (select (store t1 j1 e1) i1) (ite (= i1 j1) e1 (select t1 i1)))
)
(declare-rare-rule array-store-swap ((@T0 Type) (@T1 Type) (@T2 Type) (@T3 Type) (@T4 Type) (@T5 Type) (t1 (Array @T0 @T1)) (i1 @T2) (j1 @T3) (e1 @T4) (f1 @T5))
  :premises ((= (= i1 j1) false))
  :args (t1 i1 j1 e1 f1)
  :conclusion (= (store (store t1 i1 e1) j1 f1) (store (store t1 j1 f1) i1 e1))
)
(declare-rare-rule bool-double-not-elim ((t1 Bool))
  :args (t1)
  :conclusion (= (not (not t1)) t1)
)
(declare-rare-rule bool-not-true ((t1 Bool))
  :premises ((= t1 false))
  :args (t1)
  :conclusion (= (not t1) true)
)
(declare-rare-rule bool-not-false ((t1 Bool))
  :premises ((= t1 true))
  :args (t1)
  :conclusion (= (not t1) false)
)
(declare-rare-rule bool-eq-true ((t1 Bool))
  :args (t1)
  :conclusion (= (= t1 true) t1)
)
(declare-rare-rule bool-eq-false ((t1 Bool))
  :args (t1)
  :conclusion (= (= t1 false) (not t1))
)
(declare-rare-rule bool-eq-nrefl ((x1 Bool))
  :args (x1)
  :conclusion (= (= x1 (not x1)) false)
)
(declare-rare-rule bool-impl-false1 ((t1 Bool))
  :args (t1)
  :conclusion (= (=> t1 false) (not t1))
)
(declare-rare-rule bool-impl-false2 ((t1 Bool))
  :args (t1)
  :conclusion (= (=> false t1) true)
)
(declare-rare-rule bool-impl-true1 ((t1 Bool))
  :args (t1)
  :conclusion (= (=> t1 true) true)
)
(declare-rare-rule bool-impl-true2 ((t1 Bool))
  :args (t1)
  :conclusion (= (=> true t1) t1)
)
(declare-rare-rule bool-impl-elim ((t1 Bool) (s1 Bool))
  :args (t1 s1)
  :conclusion (= (=> t1 s1) (or (not t1) s1))
)
(declare-rare-rule bool-dual-impl-eq ((t1 Bool) (s1 Bool))
  :args (t1 s1)
  :conclusion (= (and (=> t1 s1) (=> s1 t1)) (= t1 s1))
)
(declare-rare-rule bool-and-conf ((xs1 Bool :list) (w1 Bool) (ys1 Bool :list) (zs1 Bool :list))
  :args (xs1 w1 ys1 zs1)
  :conclusion (= (and xs1 w1 ys1 (not w1) zs1) false)
)
(declare-rare-rule bool-and-conf2 ((xs1 Bool :list) (w1 Bool) (ys1 Bool :list) (zs1 Bool :list))
  :args (xs1 w1 ys1 zs1)
  :conclusion (= (and xs1 (not w1) ys1 w1 zs1) false)
)
(declare-rare-rule bool-or-taut ((xs1 Bool :list) (w1 Bool) (ys1 Bool :list) (zs1 Bool :list))
  :args (xs1 w1 ys1 zs1)
  :conclusion (= (or xs1 w1 ys1 (not w1) zs1) true)
)
(declare-rare-rule bool-or-taut2 ((xs1 Bool :list) (w1 Bool) (ys1 Bool :list) (zs1 Bool :list))
  :args (xs1 w1 ys1 zs1)
  :conclusion (= (or xs1 (not w1) ys1 w1 zs1) true)
)
(declare-rare-rule bool-or-de-morgan ((x1 Bool) (y1 Bool) (zs1 Bool :list))
  :args (x1 y1 zs1)
  :conclusion (= (not (or x1 y1 zs1)) (and (not x1) (not (or y1 zs1))))
)
(declare-rare-rule bool-implies-de-morgan ((x1 Bool) (y1 Bool))
  :args (x1 y1)
  :conclusion (= (not (=> x1 y1)) (and x1 (not y1)))
)
(declare-rare-rule bool-and-de-morgan ((x1 Bool) (y1 Bool) (zs1 Bool :list))
  :args (x1 y1 zs1)
  :conclusion (= (not (and x1 y1 zs1)) (or (not x1) (not (and y1 zs1))))
)

(declare-rare-rule bool-or-and-distrib ((y1 Bool) (y2 Bool) (ys1 Bool :list) (z1 Bool) (zs1 Bool :list))
  :args (y1 y2 ys1 z1 zs1)
  :conclusion (= (or (and y1 y2 ys1) z1 zs1) (and (or y1 z1 zs1) (or (and y2 ys1) z1 zs1)))
)
(declare-rare-rule bool-implies-or-distrib ((y1 Bool) (y2 Bool) (ys1 Bool :list) (z1 Bool))
  :args (y1 y2 ys1 z1)
  :conclusion (= (=> (or y1 y2 ys1) z1) (and (=> y1 z1) (=> (or y2 ys1) z1)))
)
(declare-rare-rule bool-xor-refl ((x1 Bool))
  :args (x1)
  :conclusion (= (xor x1 x1) false)
)
(declare-rare-rule bool-xor-nrefl ((x1 Bool))
  :args (x1)
  :conclusion (= (xor x1 (not x1)) true)
)
(declare-rare-rule bool-xor-false ((x1 Bool))
  :args (x1)
  :conclusion (= (xor x1 false) x1)
)
(declare-rare-rule bool-xor-true ((x1 Bool))
  :args (x1)
  :conclusion (= (xor x1 true) (not x1))
)
(declare-rare-rule bool-xor-comm ((x1 Bool) (y1 Bool))
  :args (x1 y1)
  :conclusion (= (xor x1 y1) (xor y1 x1))
)
(declare-rare-rule bool-xor-elim ((x1 Bool) (y1 Bool))
  :args (x1 y1)
  :conclusion (= (xor x1 y1) (= (not x1) y1))
)
(declare-rare-rule bool-not-xor-elim ((x1 Bool) (y1 Bool))
  :args (x1 y1)
  :conclusion (= (not (xor x1 y1)) (= x1 y1))
)
(declare-rare-rule bool-not-eq-elim1 ((x1 Bool) (y1 Bool))
  :args (x1 y1)
  :conclusion (= (not (= x1 y1)) (= (not x1) y1))
)
(declare-rare-rule bool-not-eq-elim2 ((x1 Bool) (y1 Bool))
  :args (x1 y1)
  :conclusion (= (not (= x1 y1)) (= x1 (not y1)))
)
(declare-rare-rule ite-neg-branch ((c1 Bool) (x1 Bool) (y1 Bool))
  :premises ((= (not y1) x1))
  :args (c1 x1 y1)
  :conclusion (= (ite c1 x1 y1) (= c1 x1))
)
(declare-rare-rule ite-then-true ((c1 Bool) (x1 Bool))
  :args (c1 x1)
  :conclusion (= (ite c1 true x1) (or c1 x1))
)
(declare-rare-rule ite-else-false ((c1 Bool) (x1 Bool))
  :args (c1 x1)
  :conclusion (= (ite c1 x1 false) (and c1 x1))
)
(declare-rare-rule ite-then-false ((c1 Bool) (x1 Bool))
  :args (c1 x1)
  :conclusion (= (ite c1 false x1) (and (not c1) x1))
)
(declare-rare-rule ite-else-true ((c1 Bool) (x1 Bool))
  :args (c1 x1)
  :conclusion (= (ite c1 x1 true) (or (not c1) x1))
)
(declare-rare-rule ite-then-lookahead-self ((c1 Bool) (x1 Bool))
  :args (c1 x1)
  :conclusion (= (ite c1 c1 x1) (ite c1 true x1))
)
(declare-rare-rule ite-else-lookahead-self ((c1 Bool) (x1 Bool))
  :args (c1 x1)
  :conclusion (= (ite c1 x1 c1) (ite c1 x1 false))
)
(declare-rare-rule ite-then-lookahead-not-self ((c1 Bool) (x1 Bool))
  :args (c1 x1)
  :conclusion (= (ite c1 (not c1) x1) (ite c1 false x1))
)
(declare-rare-rule ite-else-lookahead-not-self ((c1 Bool) (x1 Bool))
  :args (c1 x1)
  :conclusion (= (ite c1 x1 (not c1)) (ite c1 x1 true))
)
(declare-rare-rule ite-expand ((c1 Bool) (x1 Bool) (y1 Bool))
  :args (c1 x1 y1)
  :conclusion (= (ite c1 x1 y1) (and (or (not c1) x1) (or c1 y1)))
)
(declare-rare-rule bool-not-ite-elim ((c1 Bool) (x1 Bool) (y1 Bool))
  :args (c1 x1 y1)
  :conclusion (= (not (ite c1 x1 y1)) (ite c1 (not x1) (not y1)))
)
(declare-rare-rule ite-true-cond ((@T0 Type) (@T1 Type) (x1 @T0) (y1 @T1))
  :args (x1 y1)
  :conclusion (= (ite true x1 y1) x1)
)
(declare-rare-rule ite-false-cond ((@T0 Type) (@T1 Type) (x1 @T0) (y1 @T1))
  :args (x1 y1)
  :conclusion (= (ite false x1 y1) y1)
)
(declare-rare-rule ite-not-cond ((@T0 Type) (@T1 Type) (c1 Bool) (x1 @T0) (y1 @T1))
  :args (c1 x1 y1)
  :conclusion (= (ite (not c1) x1 y1) (ite c1 y1 x1))
)
(declare-rare-rule ite-eq-branch ((@T0 Type) (c1 Bool) (x1 @T0))
  :args (c1 x1)
  :conclusion (= (ite c1 x1 x1) x1)
)
(declare-rare-rule ite-then-lookahead ((@T0 Type) (@T1 Type) (@T2 Type) (c1 Bool) (x1 @T0) (y1 @T1) (z1 @T2))
  :args (c1 x1 y1 z1)
  :conclusion (= (ite c1 (ite c1 x1 y1) z1) (ite c1 x1 z1))
)
(declare-rare-rule ite-else-lookahead ((@T0 Type) (@T1 Type) (@T2 Type) (c1 Bool) (x1 @T0) (y1 @T1) (z1 @T2))
  :args (c1 x1 y1 z1)
  :conclusion (= (ite c1 x1 (ite c1 y1 z1)) (ite c1 x1 z1))
)
(declare-rare-rule ite-then-neg-lookahead ((@T0 Type) (@T1 Type) (@T2 Type) (c1 Bool) (x1 @T0) (y1 @T1) (z1 @T2))
  :args (c1 x1 y1 z1)
  :conclusion (= (ite c1 (ite (not c1) x1 y1) z1) (ite c1 y1 z1))
)
(declare-rare-rule ite-else-neg-lookahead ((@T0 Type) (@T1 Type) (@T2 Type) (c1 Bool) (x1 @T0) (y1 @T1) (z1 @T2))
  :args (c1 x1 y1 z1)
  :conclusion (= (ite c1 x1 (ite (not c1) y1 z1)) (ite c1 x1 y1))
)


(declare-rare-rule eq-refl ((@T0 Type) (t1 @T0))
  :args (t1)
  :conclusion (= (= t1 t1) true)
)
(declare-rare-rule eq-symm ((@T0 Type) (@T1 Type) (t1 @T0) (s1 @T1))
  :args (t1 s1)
  :conclusion (= (= t1 s1) (= s1 t1))
)
(declare-rare-rule eq-cond-deq ((@T0 Type) (@T1 Type) (@T2 Type) (t1 @T0) (s1 @T1) (r1 @T2))
  :premises ((= (= s1 r1) false))
  :args (t1 s1 r1)
  :conclusion (= (= (= t1 s1) (= t1 r1)) (and (not (= t1 s1)) (not (= t1 r1))))
)
(declare-rare-rule eq-ite-lift ((@T0 Type) (@T1 Type) (@T2 Type) (C1 Bool) (t1 @T0) (s1 @T1) (r1 @T2))
  :args (C1 t1 s1 r1)
  :conclusion (= (= (ite C1 t1 s1) r1) (ite C1 (= t1 r1) (= s1 r1)))
)
(declare-rare-rule distinct-binary-elim ((@T0 Type) (@T1 Type) (t1 @T0) (s1 @T1))
  :args (t1 s1)
  :conclusion (= (distinct t1 s1) (not (= t1 s1)))
)

(declare-rare-rule arith-mod-over-mod-1 ((c Int) (r Int))
  :args (c r)
  :premises ((= (= c 0) false))
  :conclusion (= (mod (mod r c) c) (mod r c)))

;;; used by Alethe's translation

(declare-rare-rule ite-eq ((@T0 Type) (C Bool) (t1 @T0) (t2 @T1))
  :args (C t1 t2)
  :conclusion (= (ite C (= (ite C t1 t2) t1) (= (ite C t1 t2) t2)) true))

(declare-rare-rule or-not-refl ((T0 Type) (t @T0) (xs Bool :list))
   :args (t xs)
   :conclusion (= (or (not (= t t)) xs) (or xs)))

(declare-rare-rule bool-not-eq-false ((t Bool))
   :args (t)
   :conclusion (= (not (= t t)) false))

(declare-rare-rule distinct-false ((@T0 Type) (t @T0) (xs @T0 :list) (ys @T0 :list) (zs @T0 :list))
   :args (t xs ys zs)
   :conclusion (= (distinct xs t ys t zs) false))

(declare-rare-rule mod-elim ((a Int) (b Int))
  :args (a b)
  :conclusion (= (mod a b) (- a (* b (div a b)))))

(declare-rare-rule is_int-elim ((x Real))
  :args (x)
  :conclusion (= (is_int x) (= x (to_real (to_int x)))))

(declare-rare-rule abs-elim-int ((t Int))
   :args (t)
   :conclusion (= (abs t) (ite (< t 0) (- t) t)))

(declare-rare-rule abs-elim-real ((t Real))
   :args (t)
   :conclusion (= (abs t) (ite (< t 0/1) (- t) t)))

(declare-rare-rule mult-tangent-lower ((@T0 Type) (x @T0) (y @T0) (a @T0) (b @T0))
   :args (x y a b)
   :conclusion (= (<= (* x y) (- (+ (* b x) (* a y)) (* a b))) (or (and (<= x a) (>= y b)) (and (>= x a) (<= y b)))))

(declare-rare-rule mult-tangent-upper ((@T0 Type) (x @T0) (y @T0) (a @T0) (b @T0))
   :args (x y a b)
   :conclusion (= (>= (* x y) (- (+ (* b x) (* a y)) (* a b))) (or (and (<= x a) (<= y b)) (and (>= x a) (>= y b)))))

;;; BV

;; (declare-rare-rule bv-concat-extract-merge ((@n0 Int) (@n1 Int) (@n2 Int) (xs1 (BitVec @n0) :list) (s1 (BitVec @n1)) (ys1 (BitVec @n2) :list) (i1 Int) (j1 Int) (j2 Int) (k1 Int))
;;   :premises ((= j2 (+ j1 1)))
;;   :args (xs1 s1 ys1 i1 j1 j2 k1)
;;   :conclusion (= (concat xs1 (extract k1 j2 s1) (extract j1 i1 s1) ys1) (concat xs1 (extract k1 i1 s1) ys1))
;; )
;; (declare-rare-rule bv-extract-extract ((@n0 Int) (x1 (BitVec @n0)) (i1 Int) (j1 Int) (k1 Int) (l1 Int) (ll1 Int) (kk1 Int))
;;   :premises ((= ll1 (+ i1 l1)) (= kk1 (+ i1 k1)))
;;   :args (x1 i1 j1 k1 l1 ll1 kk1)
;;   :conclusion (= (extract l1 k1 (extract j1 i1 x1)) (extract ll1 kk1 x1))
;; )
;; (declare-rare-rule bv-extract-whole ((@n0 Int) (x1 (BitVec @n0)) (n1 Int))
;;   :premises ((= (>= n1 (- (@bvsize x1) 1)) true))
;;   :args (x1 n1)
;;   :conclusion (= (extract n1 0 x1) x1)
;; )
;; (declare-rare-rule bv-extract-concat-1 ((@n0 Int) (@n1 Int) (@n2 Int) (x1 (BitVec @n0)) (xs1 (BitVec @n1) :list) (y1 (BitVec @n2)) (i1 Int) (j1 Int))
;;   :premises ((= (<= j1 (@bvsize x1)) true))
;;   :args (x1 xs1 y1 i1 j1)
;;   :conclusion (= (extract j1 i1 (concat xs1 y1 x1)) (extract j1 i1 x1))
;; )
;; (declare-rare-rule bv-extract-concat-2 ((@n0 Int) (@n1 Int) (@n2 Int) (x1 (BitVec @n0)) (xs1 (BitVec @n1) :list) (y1 (BitVec @n2)) (i1 Int) (j1 Int) (u1 Int) (u2 Int))
;;   :premises ((= (< i1 (@bvsize x1)) true) (= (>= j1 (@bvsize x1)) true) (= u1 (- j1 (@bvsize x1))) (= u2 (- (@bvsize x1) 1)))
;;   :args (x1 xs1 y1 i1 j1 u1 u2)
;;   :conclusion (= (extract j1 i1 (concat xs1 y1 x1)) (concat (extract u1 0 (concat xs1 y1)) (extract u2 i1 x1)))
;; )
;; (declare-rare-rule bv-extract-concat-3 ((@n0 Int) (@n1 Int) (@n2 Int) (x1 (BitVec @n0)) (y1 (BitVec @n1)) (xs1 (BitVec @n2) :list) (i1 Int) (j1 Int) (u1 Int) (l1 Int))
;;   :premises ((= (>= i1 (@bvsize x1)) true) (= u1 (- j1 (@bvsize x1))) (= l1 (- i1 (@bvsize x1))))
;;   :args (x1 y1 xs1 i1 j1 u1 l1)
;;   :conclusion (= (extract j1 i1 (concat xs1 y1 x1)) (extract u1 l1 (concat xs1 y1)))
;; )
;; (declare-rare-rule bv-extract-concat-4 ((@n0 Int) (@n1 Int) (@n2 Int) (x1 (BitVec @n0)) (y1 (BitVec @n1)) (xs1 (BitVec @n2) :list) (i1 Int) (j1 Int))
;;   :premises ((= (< j1 (- (@bvsize (concat x1 y1 xs1)) (@bvsize x1))) true))
;;   :args (x1 y1 xs1 i1 j1)
;;   :conclusion (= (extract j1 i1 (concat x1 xs1 y1)) (extract j1 i1 (concat xs1 y1)))
;; )
;; (declare-rare-rule bv-eq-extract-elim1 ((@n0 Int) (@n1 Int) (x1 (BitVec @n0)) (y1 (BitVec @n1)) (i1 Int) (j1 Int) (wm1 Int) (jp1 Int) (im1 Int))
;;   :premises ((= wm1 (- (@bvsize x1) 1)) (= jp1 (+ j1 1)) (= im1 (- i1 1)) (= (> wm1 j1) true) (= (> i1 0) true))
;;   :args (x1 y1 i1 j1 wm1 jp1 im1)
;;   :conclusion (= (= (extract j1 i1 x1) y1) (= x1 (concat (extract wm1 jp1 x1) y1 (extract im1 0 x1))))
;; )
;; (declare-rare-rule bv-eq-extract-elim2 ((@n0 Int) (@n1 Int) (x1 (BitVec @n0)) (y1 (BitVec @n1)) (j1 Int) (wm1 Int) (jp1 Int))
;;   :premises ((= wm1 (- (@bvsize x1) 1)) (= jp1 (+ j1 1)) (= (> wm1 j1) true))
;;   :args (x1 y1 j1 wm1 jp1)
;;   :conclusion (= (= (extract j1 0 x1) y1) (= x1 (concat (extract wm1 jp1 x1) y1)))
;; )
;; (declare-rare-rule bv-eq-extract-elim3 ((@n0 Int) (@n1 Int) (x1 (BitVec @n0)) (y1 (BitVec @n1)) (i1 Int) (j1 Int) (im1 Int))
;;   :premises ((= j1 (- (@bvsize x1) 1)) (= im1 (- i1 1)) (= (> i1 0) true))
;;   :args (x1 y1 i1 j1 im1)
;;   :conclusion (= (= (extract j1 i1 x1) y1) (= x1 (concat y1 (extract im1 0 x1))))
;; )
"#

/-- The rule table, in the order of the rule file. -/
def rules : Array RareRule := #[
  { name := "arith-div-total-zero-real", args := #[.term], premises := 0, thms := #[⟨.int, ``arith_div_total_zero_real_int, true⟩, ⟨.rat, ``arith_div_total_zero_real_rat, true⟩] },
  { name := "arith-div-total-zero-int", args := #[.term], premises := 0, thms := #[⟨.int, ``arith_div_total_zero_int_int, true⟩, ⟨.rat, ``arith_div_total_zero_int_rat, true⟩] },
  { name := "arith-int-div-total-zero", args := #[.term], premises := 0, thms := #[⟨.mono, ``arith_int_div_total_zero, true⟩] },
  { name := "arith-int-mod-total-zero", args := #[.term], premises := 0, thms := #[⟨.mono, ``arith_int_mod_total_zero, true⟩] },
  { name := "arith-int-div-total", args := #[.term, .term], premises := 1, thms := #[⟨.mono, ``arith_int_div_total, true⟩] },
  { name := "arith-int-div-total-one", args := #[.term], premises := 0, thms := #[⟨.mono, ``arith_int_div_total_one, true⟩] },
  { name := "arith-int-div-total-neg", args := #[.term, .term], premises := 1, thms := #[⟨.mono, ``arith_int_div_total_neg, true⟩] },
  { name := "arith-int-mod-total", args := #[.term, .term], premises := 1, thms := #[⟨.mono, ``arith_int_mod_total, true⟩] },
  { name := "arith-int-mod-total-one", args := #[.term], premises := 0, thms := #[⟨.mono, ``arith_int_mod_total_one, true⟩] },
  { name := "arith-int-mod-total-neg", args := #[.term, .term], premises := 1, thms := #[⟨.mono, ``arith_int_mod_total_neg, true⟩] },
  { name := "arith-elim-gt", args := #[.term, .term], premises := 0, thms := #[⟨.int, ``arith_elim_gt_int, true⟩, ⟨.rat, ``arith_elim_gt_rat, true⟩] },
  { name := "arith-elim-lt", args := #[.term, .term], premises := 0, thms := #[⟨.int, ``arith_elim_lt_int, true⟩, ⟨.rat, ``arith_elim_lt_rat, true⟩] },
  { name := "arith-elim-int-gt", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``arith_elim_int_gt, true⟩] },
  { name := "arith-elim-int-lt", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``arith_elim_int_lt, true⟩] },
  { name := "arith-elim-leq", args := #[.term, .term], premises := 0, thms := #[⟨.int, ``arith_elim_leq_int, true⟩, ⟨.rat, ``arith_elim_leq_rat, true⟩] },
  { name := "arith-leq-norm", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``arith_leq_norm, true⟩] },
  { name := "arith-geq-tighten", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``arith_geq_tighten, true⟩] },
  { name := "arith-geq-norm1-int", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``arith_geq_norm1_int, true⟩] },
  { name := "arith-geq-norm1-real", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``arith_geq_norm1_real, true⟩] },
  { name := "arith-eq-elim-real", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``arith_eq_elim_real, true⟩] },
  { name := "arith-eq-elim-int", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``arith_eq_elim_int, true⟩] },
  { name := "arith-to-int-elim-to-real", args := #[.term], premises := 0, thms := #[⟨.int, ``arith_to_int_elim_to_real_int, true⟩, ⟨.rat, ``arith_to_int_elim_to_real_rat, true⟩] },
  { name := "arith-div-elim-to-real1", args := #[.term, .term], premises := 0, thms := #[⟨.int, ``arith_div_elim_to_real1_int, true⟩, ⟨.rat, ``arith_div_elim_to_real1_rat, true⟩] },
  { name := "arith-div-elim-to-real2", args := #[.term, .term], premises := 0, thms := #[⟨.int, ``arith_div_elim_to_real2_int, true⟩, ⟨.rat, ``arith_div_elim_to_real2_rat, true⟩] },
  { name := "arith-mod-over-mod", args := #[.term, .list, .term, .list], premises := 1, thms := #[⟨.mono, ``arith_mod_over_mod, true⟩] },
  { name := "arith-int-eq-conflict", args := #[.term, .term], premises := 1, thms := #[⟨.mono, ``arith_int_eq_conflict, true⟩] },
  { name := "arith-int-geq-tighten", args := #[.term, .term, .term], premises := 2, thms := #[⟨.mono, ``arith_int_geq_tighten, true⟩] },
  { name := "arith-abs-eq", args := #[.term, .term], premises := 0, thms := #[⟨.int, ``arith_abs_eq_int, true⟩, ⟨.rat, ``arith_abs_eq_rat, true⟩] },
  { name := "arith-abs-int-gt", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``arith_abs_int_gt, true⟩] },
  { name := "arith-abs-real-gt", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``arith_abs_real_gt, true⟩] },
  { name := "arith-geq-ite-lift", args := #[.term, .term, .term, .term], premises := 0, thms := #[⟨.int, ``arith_geq_ite_lift_int, true⟩, ⟨.rat, ``arith_geq_ite_lift_rat, true⟩] },
  { name := "arith-leq-ite-lift", args := #[.term, .term, .term, .term], premises := 0, thms := #[⟨.int, ``arith_leq_ite_lift_int, true⟩, ⟨.rat, ``arith_leq_ite_lift_rat, true⟩] },
  { name := "arith-min-lt1", args := #[.term, .term], premises := 0, thms := #[⟨.int, ``arith_min_lt1_int, true⟩, ⟨.rat, ``arith_min_lt1_rat, true⟩] },
  { name := "arith-min-lt2", args := #[.term, .term], premises := 0, thms := #[⟨.int, ``arith_min_lt2_int, true⟩, ⟨.rat, ``arith_min_lt2_rat, true⟩] },
  { name := "arith-max-geq1", args := #[.term, .term], premises := 0, thms := #[⟨.int, ``arith_max_geq1_int, true⟩, ⟨.rat, ``arith_max_geq1_rat, true⟩] },
  { name := "arith-max-geq2", args := #[.term, .term], premises := 0, thms := #[⟨.int, ``arith_max_geq2_int, true⟩, ⟨.rat, ``arith_max_geq2_rat, true⟩] },
  { name := "array-read-over-write", args := #[.term, .term, .term], premises := 0, thms := #[] },
  { name := "array-read-over-write2", args := #[.term, .term, .term, .term], premises := 1, thms := #[] },
  { name := "array-store-overwrite", args := #[.term, .term, .term, .term], premises := 0, thms := #[] },
  { name := "array-store-self", args := #[.term, .term], premises := 0, thms := #[] },
  { name := "array-read-over-write-split", args := #[.term, .term, .term, .term], premises := 0, thms := #[] },
  { name := "array-store-swap", args := #[.term, .term, .term, .term, .term], premises := 1, thms := #[] },
  { name := "bool-double-not-elim", args := #[.term], premises := 0, thms := #[⟨.mono, ``bool_double_not_elim, true⟩] },
  { name := "bool-not-true", args := #[.term], premises := 1, thms := #[⟨.mono, ``bool_not_true, true⟩] },
  { name := "bool-not-false", args := #[.term], premises := 1, thms := #[⟨.mono, ``bool_not_false, true⟩] },
  { name := "bool-eq-true", args := #[.term], premises := 0, thms := #[⟨.mono, ``bool_eq_true, true⟩] },
  { name := "bool-eq-false", args := #[.term], premises := 0, thms := #[⟨.mono, ``bool_eq_false, true⟩] },
  { name := "bool-eq-nrefl", args := #[.term], premises := 0, thms := #[⟨.mono, ``bool_eq_nrefl, true⟩] },
  { name := "bool-impl-false1", args := #[.term], premises := 0, thms := #[⟨.mono, ``bool_impl_false1, true⟩] },
  { name := "bool-impl-false2", args := #[.term], premises := 0, thms := #[⟨.mono, ``bool_impl_false2, true⟩] },
  { name := "bool-impl-true1", args := #[.term], premises := 0, thms := #[⟨.mono, ``bool_impl_true1, true⟩] },
  { name := "bool-impl-true2", args := #[.term], premises := 0, thms := #[⟨.mono, ``bool_impl_true2, true⟩] },
  { name := "bool-impl-elim", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``bool_impl_elim, true⟩] },
  { name := "bool-dual-impl-eq", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``bool_dual_impl_eq, true⟩] },
  { name := "bool-and-conf", args := #[.list, .term, .list, .list], premises := 0, thms := #[⟨.mono, ``bool_and_conf, true⟩] },
  { name := "bool-and-conf2", args := #[.list, .term, .list, .list], premises := 0, thms := #[⟨.mono, ``bool_and_conf2, true⟩] },
  { name := "bool-or-taut", args := #[.list, .term, .list, .list], premises := 0, thms := #[⟨.mono, ``bool_or_taut, true⟩] },
  { name := "bool-or-taut2", args := #[.list, .term, .list, .list], premises := 0, thms := #[⟨.mono, ``bool_or_taut2, true⟩] },
  { name := "bool-or-de-morgan", args := #[.term, .term, .list], premises := 0, thms := #[⟨.mono, ``bool_or_de_morgan, true⟩] },
  { name := "bool-implies-de-morgan", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``bool_implies_de_morgan, true⟩] },
  { name := "bool-and-de-morgan", args := #[.term, .term, .list], premises := 0, thms := #[⟨.mono, ``bool_and_de_morgan, true⟩] },
  { name := "bool-or-and-distrib", args := #[.term, .term, .list, .term, .list], premises := 0, thms := #[⟨.mono, ``bool_or_and_distrib, true⟩] },
  { name := "bool-implies-or-distrib", args := #[.term, .term, .list, .term], premises := 0, thms := #[⟨.mono, ``bool_implies_or_distrib, true⟩] },
  { name := "bool-xor-refl", args := #[.term], premises := 0, thms := #[⟨.mono, ``bool_xor_refl, true⟩] },
  { name := "bool-xor-nrefl", args := #[.term], premises := 0, thms := #[⟨.mono, ``bool_xor_nrefl, true⟩] },
  { name := "bool-xor-false", args := #[.term], premises := 0, thms := #[⟨.mono, ``bool_xor_false, true⟩] },
  { name := "bool-xor-true", args := #[.term], premises := 0, thms := #[⟨.mono, ``bool_xor_true, true⟩] },
  { name := "bool-xor-comm", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``bool_xor_comm, true⟩] },
  { name := "bool-xor-elim", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``bool_xor_elim, true⟩] },
  { name := "bool-not-xor-elim", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``bool_not_xor_elim, true⟩] },
  { name := "bool-not-eq-elim1", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``bool_not_eq_elim1, true⟩] },
  { name := "bool-not-eq-elim2", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``bool_not_eq_elim2, true⟩] },
  { name := "ite-neg-branch", args := #[.term, .term, .term], premises := 1, thms := #[⟨.mono, ``ite_neg_branch, true⟩] },
  { name := "ite-then-true", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``ite_then_true, true⟩] },
  { name := "ite-else-false", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``ite_else_false, true⟩] },
  { name := "ite-then-false", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``ite_then_false, true⟩] },
  { name := "ite-else-true", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``ite_else_true, true⟩] },
  { name := "ite-then-lookahead-self", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``ite_then_lookahead_self, true⟩] },
  { name := "ite-else-lookahead-self", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``ite_else_lookahead_self, true⟩] },
  { name := "ite-then-lookahead-not-self", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``ite_then_lookahead_not_self, true⟩] },
  { name := "ite-else-lookahead-not-self", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``ite_else_lookahead_not_self, true⟩] },
  { name := "ite-expand", args := #[.term, .term, .term], premises := 0, thms := #[⟨.mono, ``ite_expand, true⟩] },
  { name := "bool-not-ite-elim", args := #[.term, .term, .term], premises := 0, thms := #[⟨.mono, ``bool_not_ite_elim, true⟩] },
  { name := "ite-true-cond", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``ite_true_cond, true⟩] },
  { name := "ite-false-cond", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``ite_false_cond, true⟩] },
  { name := "ite-not-cond", args := #[.term, .term, .term], premises := 0, thms := #[⟨.mono, ``ite_not_cond, true⟩] },
  { name := "ite-eq-branch", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``ite_eq_branch, true⟩] },
  { name := "ite-then-lookahead", args := #[.term, .term, .term, .term], premises := 0, thms := #[⟨.mono, ``ite_then_lookahead, true⟩] },
  { name := "ite-else-lookahead", args := #[.term, .term, .term, .term], premises := 0, thms := #[⟨.mono, ``ite_else_lookahead, true⟩] },
  { name := "ite-then-neg-lookahead", args := #[.term, .term, .term, .term], premises := 0, thms := #[⟨.mono, ``ite_then_neg_lookahead, true⟩] },
  { name := "ite-else-neg-lookahead", args := #[.term, .term, .term, .term], premises := 0, thms := #[⟨.mono, ``ite_else_neg_lookahead, true⟩] },
  { name := "eq-refl", args := #[.term], premises := 0, thms := #[⟨.mono, ``eq_refl, true⟩] },
  { name := "eq-symm", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``eq_symm, true⟩] },
  { name := "eq-cond-deq", args := #[.term, .term, .term], premises := 1, thms := #[⟨.mono, ``eq_cond_deq, true⟩] },
  { name := "eq-ite-lift", args := #[.term, .term, .term, .term], premises := 0, thms := #[⟨.mono, ``eq_ite_lift, true⟩] },
  { name := "distinct-binary-elim", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``distinct_binary_elim, true⟩] },
  { name := "arith-mod-over-mod-1", args := #[.term, .term], premises := 1, thms := #[⟨.mono, ``arith_mod_over_mod_1, true⟩] },
  { name := "ite-eq", args := #[.term, .term, .term], premises := 0, thms := #[⟨.mono, ``ite_eq, true⟩] },
  { name := "or-not-refl", args := #[.term, .list], premises := 0, thms := #[⟨.mono, ``or_not_refl, true⟩] },
  { name := "bool-not-eq-false", args := #[.term], premises := 0, thms := #[⟨.mono, ``bool_not_eq_false, true⟩] },
  { name := "distinct-false", args := #[.term, .list, .list, .list], premises := 0, thms := #[] },
  { name := "mod-elim", args := #[.term, .term], premises := 0, thms := #[⟨.mono, ``mod_elim, true⟩] },
  { name := "is_int-elim", args := #[.term], premises := 0, thms := #[⟨.mono, ``is_int_elim, true⟩] },
  { name := "abs-elim-int", args := #[.term], premises := 0, thms := #[⟨.mono, ``abs_elim_int, true⟩] },
  { name := "abs-elim-real", args := #[.term], premises := 0, thms := #[⟨.mono, ``abs_elim_real, true⟩] },
  { name := "mult-tangent-lower", args := #[.term, .term, .term, .term], premises := 0, thms := #[⟨.int, ``mult_tangent_lower_int, false⟩, ⟨.rat, ``mult_tangent_lower_rat, false⟩] },
  { name := "mult-tangent-upper", args := #[.term, .term, .term, .term], premises := 0, thms := #[⟨.int, ``mult_tangent_upper_int, false⟩, ⟨.rat, ``mult_tangent_upper_rat, false⟩] }
]

end Smt.Alethe.Rare